version: "3.7"

services:
  language-service:
    container_name: language-service
    image: ${DLTK_NLP_IMAGE}
    init: true
    command: >
      sh -c "python manage.py migrate &
             gunicorn --bind 0.0.0.0:8189 dltk_language.wsgi"
    restart: always
    ports:
      - "${INSTANCE_PORT}:8189"

    env_file:
        - .env

networks:
  default:
    external:
        name: dltk