---
# tasks file for dltk-ai-disable-auth-1

- name: Create dltk-ai directory if it does not exist
  ansible.builtin.file:
    path: "{{ folderpath }}/dltk-ai"
    state: directory
    mode: '0755'

- name: running docker-compose.yml file to stop dltk-influxdb container
  command: chdir="{{ folderpath }}/dltk-ai/db/" docker-compose stop dltk-influxdb

- name: running docker-compose.yml file to start dltk-influxdb container | Setting up OpenDltk services, this may take some time.
  command: chdir="{{ folderpath }}/dltk-ai/db/" docker-compose up -d dltk-influxdb
