---
# tasks file for nlp.yml

- name: Create dltk-ai directory if it does not exist
  ansible.builtin.file:
    path: "{{ folderpath }}/dltk-ai"
    state: directory
    mode: '0755'

- name: Create dltk-ai directory if it does not exist
  ansible.builtin.file:
    path: /usr/dltk-ai
    state: directory
    mode: '0755'

- name: copying the required folder from ansible to remote machine
  copy:
    src: "{{ playbook_dir }}/../../nlp"
    dest: "{{ folderpath }}/dltk-ai/"

- name: running docker-compose.yml file to stop dltk-nlp container
  command: chdir="{{ folderpath }}/dltk-ai/nlp/" docker-compose down

- name: Pause for 5 sec
  pause:
    seconds: 5

- name: running docker-compose.yml file to start dltk-nlp container | Setting up OpenDltk services, this may take some time.
  command: chdir="{{ folderpath }}/dltk-ai/nlp/" docker-compose up -d
