- hosts: dltk-ai-base-host
  roles:
    - dltk-ai-disable-auth-db-migrations

- hosts: dltk-ai-db-host
  roles:
    - dltk-ai-disable-auth-1

- hosts: dltk-ai-base-host
  roles:
    - dltk-ai-disable-auth-2
 
- hosts: dltk-ai-base-host
  roles:
    - dltk-ai-disable-web
