---
# tasks file for dltk-ai-disable-auth-db-migrations

- name: copying the required folder from ansible to remote machine
  copy:
    src: "{{ playbook_dir }}/../../pgdump"
    dest: "{{ folderpath }}/dltk-ai/"

- name: running docker-compose.yml file to stop dltk-db-migrations container
  command: chdir="{{ folderpath }}/dltk-ai/base/" docker-compose down dltk-db-migrations 

- name: running docker-compose.yml file to start dltk-db-migrations container | Setting up OpenDltk services, this may take some time.
  command: chdir="{{ folderpath }}/dltk-ai/base/" docker-compose up -d dltk-db-migrations 
