---
# tasks file for dltk-ai-cv-wrapper

- name: Create dltk-ai directory if it does not exist
  ansible.builtin.file:
    path: "{{ folderpath }}/dltk-ai"
    state: directory
    mode: '0755'

- name: Create dltk-ai directory if it does not exist
  ansible.builtin.file:
    path: /usr/dltk-ai
    state: directory
    mode: '0755'

- name: copying the required folder from ansible to remote machine
  copy:
    src: "{{ playbook_dir }}/../../cv/wrapper"
    dest: "{{ folderpath }}/dltk-ai/"

- name: running docker-compose.yml file to stop dltk-computer-vision container 
  command: chdir="{{ folderpath }}/dltk-ai/wrapper" docker-compose down dltk-computer-vision

- name: Pause for 5 sec
  pause:
    seconds: 5

- name: running docker-compose.yml file to start dltk-computer-vision container | Setting up OpenDltk services, this may take some time.
  command: chdir="{{ folderpath }}/dltk-ai/wrapper" docker-compose up -d dltk-computer-vision

